# Generated by Django 5.0.6 on 2025-08-04 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_analyzer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_correction', models.BooleanField()),
                ('feedback_comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news_analyzer.newsarticle')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
