# Generated by Django 5.0.6 on 2025-08-04 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_analyzer', '0002_analysisfeedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('twitter', 'Twitter/X'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('youtube', 'YouTube'), ('reddit', 'Reddit'), ('telegram', 'Telegram'), ('whatsapp', 'WhatsApp'), ('other', 'Other')], max_length=20)),
                ('content', models.TextField()),
                ('author', models.CharField(blank=True, max_length=200)),
                ('post_id', models.CharField(blank=True, max_length=100)),
                ('url', models.URLField(blank=True)),
                ('engagement_metrics', models.JSONField(blank=True, default=dict)),
                ('is_fake', models.BooleanField(blank=True, null=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('viral_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analyzed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SocialMediaAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_detection_score', models.FloatField(blank=True, null=True)),
                ('engagement_manipulation_score', models.FloatField(blank=True, null=True)),
                ('content_credibility_score', models.FloatField(blank=True, null=True)),
                ('source_verification_score', models.FloatField(blank=True, null=True)),
                ('viral_pattern_score', models.FloatField(blank=True, null=True)),
                ('fact_check_results', models.JSONField(blank=True, default=dict)),
                ('hashtag_analysis', models.JSONField(blank=True, default=dict)),
                ('sentiment_analysis', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news_analyzer.socialmediapost')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
