# Generated by Django 5.0.6 on 2025-08-10 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_analyzer', '0003_socialmediapost_socialmediaanalysis'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SocialMediaAnalysis',
        ),
        migrations.DeleteModel(
            name='SocialMediaPost',
        ),
    ]
